
public class MyException1 extends System.Exception {
    let myField = throw test /* please work "test"*/;

    public doSomething () {
        throw new MyException1();
    }

    public somethingElse (one, two, three, four, five) {
        try {
            doSomething();
        }
        catch {
            _: printfn /* this is the default handler */;
        }
        finally {
            // take out the trash
            one.Dispose();
        }
    }
}
